version: 2
jobs:
  "node-11":
    docker:
      - image: circleci/node:11.9
    working_directory: ~/pxpost
    steps:
      - checkout

      - run: npm install
      # run tests!
      - run: npm test

  "node-10":
    docker:
      - image: circleci/node:10
    working_directory: ~/pxpost
    steps:
      - checkout

      - run: npm install
      # run tests!
      - run: npm test

  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/pxpost
    steps:
      - checkout

      - run: npm install
      # run tests!
      - run: npm test

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - "master"
    jobs:
      - "node-11"
      - "node-10"
      - "node-8"
  build:
    jobs:
      - "node-11"
      - "node-10"
      - "node-8"
